<a href="https://colab.research.google.com/github/harishmuh/Python-for-Data-Science-Analysis/blob/main/Pandas_and_Numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python for data analysis exercise**
---

In [1]:
# importing library
import numpy as np
import pandas as pd

**Number 1**

Create an array with the arrange command, with the start and end values as input!
From the resulting array, create 2- and 3-dimensional versions!

In [2]:
# Input
start = 1
finish = 28

In [3]:
# Creating 1 Dimensional Array using list comperhension
array_1d = [i for i in range(start, finish)]
print("1 Dimensional Array:")
print(array_1d)

1 Dimensional Array:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

In [4]:
# Creating 1 Dimensional Array using list comperhension using numpy.arange
array_1d = np.arange(1, 28)
print("1-Dimensional Array (NumPy):")
print(array_1d)

1-Dimensional Array (NumPy):
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]

In [5]:
# 2D
array_2d = array_1d.reshape(3, 9)
print("2D Array:")
print(array_2d)

2D Array:
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]

In [6]:
#3D
array_3d = array_1d.reshape(3, 3, 3)
print("3D Array:")
print(array_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

**Number 2**

* Create a 1-dimensional array
* Convert the 1-dimensional array into a 2-dimensional matrix!
* After converting to 2-dimensional form, reverse the order of the data in each row! For example, from 1, 2, 3 to 3, 2, 1.

In [7]:
# Create a 1-dimensional array
array_1d = np.array([23, 19, 15, 30, 30, 47, 44, 26, 41, 5, 9, 17, 46, 19, 21, 32])

print("1-Dimensional Array:")
print(array_1d)

1-Dimensional Array:
[23 19 15 30 30 47 44 26 41  5  9 17 46 19 21 32]

In [8]:
# 2D
array_2d = array_1d.reshape(4, 4)
print("2D Array:")
print(array_2d)

2D Array:
[[23 19 15 30]
 [30 47 44 26]
 [41  5  9 17]
 [46 19 21 32]]

In [9]:
# Swap the positions of 1,2,3 to 3,2,1
# Reverse the order of elements in each row (reverse columns)
reversed_arr = array_2d[:, ::-1]

# Display the result
print("Reversed array")
print(reversed_arr)

Reversed array
[[30 15 19 23]
 [26 44 47 30]
 [17  9  5 41]
 [32 21 19 46]]

**No. 3**

* Create a 2-dimensional array with dimensions of 10 x 10!
* The contents of the array are:
  * The outer edge is the number 4.
  * Every other edge is 0.

In [10]:
# Create a 10x10 array containing all 0s
array = np.zeros((10, 10), dtype=int)

# Change the outer values to 4
array[0, :] = 4 # top row
array[-1, :] = 4 # bottom row
array[:, 0] = 4 # left column
array[:, -1] = 4 # right column

print(array)

[[4 4 4 4 4 4 4 4 4 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 0 0 0 0 0 0 0 0 4]
 [4 4 4 4 4 4 4 4 4 4]]

**No. 4**

Create a Series using the Pandas library!
* The indexes in the Series are lowercase letters from a to z.
* The data for each index is a number from 1 to 26.

In [11]:
import string

# Create an index for letters a to z
index = list(string.ascii_lowercase) # ['a', 'b', ..., 'z']

# Create data from 1 to 26
data = list(range(1, 27))

# Create a Series
series = pd.Series(data=data, index=index)

print(series)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

**Number 5**

* Create a series using 100 random integer numbers from 1 to 5!
* Calculate the frequency of each number!
* Find the two values with the highest frequency!

In [12]:
# Create a Series with 100 random numbers between 1 and 5
random_series = pd.Series(np.random.randint(1, 6, size=100))
random_series

0     4
1     2
2     2
3     3
4     4
     ..
95    5
96    2
97    5
98    4
99    5
Length: 100, dtype: int64

In [13]:
# Count the frequency of occurrence of each number
frequencies = random_series.value_counts()
# Display the frequency of all numbers
print("Frequencies of all values:")
print(frequencies)

Frequencies of all values:
2    26
4    24
5    24
3    14
1    12
Name: count, dtype: int64

In [14]:
# Take the 2 values with the highest frequency
top_2 = frequencies.head(2)
print("\nTop 2 most frequent values:")
print(top_2)

Top 2 most frequent values:
2    26
4    24
Name: count, dtype: int64

**Number 6**

* Import the "seaborn" library. Then, load the data named "MPG"!
* Display the top 5 data points in the DataFrame from the "MPG" data!
* Display descriptive statistics or Describe data other than numeric data!
* Display all column names in the DataFrame!
* Count the number of missing values (empty data) in each column!

In [16]:
# Import data seaborn and load data 'MPG'
import seaborn as sns
mpg = sns.load_dataset('mpg')

In [17]:
# The top 5 data
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [18]:
# Display descriptive statistics in addition to numeric data
mpg.describe(include=['object'])

       origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [19]:
# Count the number of missing values in each column
mpg.isna().sum().to_frame('Number of Missing Values')

              Number of Missing Values
mpg                                  0
cylinders                            0
displacement                         0
horsepower                           6
weight                               0
acceleration                         0
model_year                           0
origin                               0
name                                 0

**Number 7**

Import the "seaborn" library, then load the data named "MPG"!
Display the missing value (empty data) in the "horsepower" column!
Display the index of the missing value's location!

In [20]:
# Filter rows that have missing values in the 'horsepower' column
missing_rows = mpg[mpg['horsepower'].isnull()]

missing_rows

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
126,21.0,6,200.0,NaN,2875,17.0,74,usa,ford maverick
330,40.9,4,85.0,NaN,1835,17.3,80,europe,renault lecar deluxe
336,23.6,4,140.0,NaN,2905,14.3,80,usa,ford mustang cobra
354,34.5,4,100.0,NaN,2320,15.8,81,europe,renault 18i
374,23.0,4,151.0,NaN,3035,20.5,82,usa,amc concord dl

In [21]:
# Display the missing value location index
#mpg.index[missing_rows.index]
print("Index location missing value:")
print(missing_rows.index)

Index location missing value:
Index([32, 126, 330, 336, 354, 374], dtype='int64')

In [22]:
# Show missing values in the 'horsepower' column
missing_hp = mpg['horsepower'].isnull()
print("Missing values in 'horsepower':")
#print(mpg['horsepower'][missing_hp])
mpg['horsepower'][missing_hp]

Missing values in 'horsepower':

32    NaN
126   NaN
330   NaN
336   NaN
354   NaN
374   NaN
Name: horsepower, dtype: float64

In [23]:
# Display the missing value location index
print("\nIndex of missing values in 'horsepower':")
print(mpg.index[missing_hp])

Index of missing values in 'horsepower':
Index([32, 126, 330, 336, 354, 374], dtype='int64')

In [25]:
# Drop missing values in the 'horsepower' column
mpg.dropna(subset=['horsepower'], inplace=True)
mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

**Number 8**

* Import the "seaborn" library, then load the data named "MPG"!
* Group the data based on the "origin" column! Display the average "horsepower" for each origin group!

In [26]:
# Calculate average horsepower based on origin
avg_hp_per_origin = mpg.groupby('origin')['horsepower'].mean()

avg_hp_per_origin

origin
europe     80.558824
japan      79.835443
usa       119.048980
Name: horsepower, dtype: float64

**Number 9**

* Import the "seaborn" library, then load the data named "MPG"!
* Create a new column named 'horse_origin'!
* This 'horse_origin' column must be populated using the contains function:
* If the 'horsepower' value is <105, display 'lower' + 'origin name' in the same row. For example, 'lower USA'.
* If the 'horsepower' value is >= 105, display 'upper' + 'origin name'.

In [27]:
# Create a regular function
def classify_horse_origin(row):
  if row['horsepower'] < 105:
    return 'lower ' + row['origin'].title()
  else:
    return 'upper ' + row['origin'].title()

# Apply the function to each row of the dataframe
mpg['horse_origin'] = mpg.apply(classify_horse_origin, axis=1)

# Display the results
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,horse_origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,upper Usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,upper Usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,upper Usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,upper Usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,upper Usa

**Number 10**

* Import the "seaborn" library, then load the data named "MPG"!
* Group the "weight" column based on the "origin" column by aggregating the mean, standard deviation, sum, count, min, and max!
* Reset the index so that the "origin" column is no longer an index but remains a column!

In [28]:
# Grouping and aggregation
grouped_weight = mpg.groupby('origin')['weight'].agg(['mean', 'std', 'sum', 'count', 'min', 'max'])
grouped_weight

               mean         std     sum  count   min   max
origin
europe  2433.470588  491.813867  165476     68  1825  3820
japan   2221.227848  320.497248  175477     79  1613  2930
usa     3372.489796  795.346690  826260    245  1800  5140

In [29]:
# Grouping and aggregation (after resetting index())
reset = grouped_weight.reset_index()
reset

   origin         mean         std     sum  count   min   max
0  europe  2433.470588  491.813867  165476     68  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3372.489796  795.346690  826260    245  1800  5140