<a href="https://colab.research.google.com/github/harishmuh/Python-for-Data-Science-Analysis/blob/main/Pandas_I_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas I Exercise

**Step 1. Import the required libraries.**

In [1]:
import pandas as pd
import numpy as np

**Step 2. Create a dictionary to create a DataFrame with 5 keys and each key has a value in the form of a list with 10 items. The contents of the dictionary follow the output of Step 3.**

In [10]:
dict_employees = {
'Name' : ['Andi', 'Budi', 'Caca', 'Dedi', 'Erika', 'Fahri', 'Gina', 'Hani', 'Irja', 'Jarot'],
'Age' : [24, 25, 30, 32, 28, 24, 29, 31, 30, 29],
'Gender' : ['Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male'],
'Occupation' : ['Data Analyst', 'Data Engineer', 'Data Scientist', 'Data Scientist', 'Data Analyst', 'Data Engineer', 'ML Engineer', 'ML Researcher', 'BI Analyst', 'Data Analyst'],
'Domicile' : ['Jakarta', 'South Tangerang', 'Jakarta', 'Bandung', 'Jakarta', 'Surabaya', 'Bandung', 'Yogyakarta', 'Jakarta', 'South Tangerang']
}

**Step 3. Convert the dictionary from Step.2 into DataFrame form and save it into a new variable named df.**

In [11]:
df = pd.DataFrame(data=dict_employees)
df

    Name  Age  Gender      Occupation         Domicile
0   Andi   24    Male    Data Analyst          Jakarta
1   Budi   25    Male   Data Engineer  South Tangerang
2   Caca   30  Female  Data Scientist          Jakarta
3   Dedi   32    Male  Data Scientist          Bandung
4  Erika   28  Female    Data Analyst          Jakarta
5  Fahri   24    Male   Data Engineer         Surabaya
6   Gina   29  Female     ML Engineer          Bandung
7   Hani   31  Female   ML Researcher       Yogyakarta
8   Irja   30    Male      BI Analyst          Jakarta
9  Jarot   29    Male    Data Analyst  South Tangerang

**Step 4. Change the order of the columns to be as follows: Name, Gender, Age, Domicile, Occupation.**

In [12]:
df = df[['Name', 'Gender', 'Age', 'Domicile', 'Occupation']].copy()
df

    Name  Gender  Age         Domicile      Occupation
0   Andi    Male   24          Jakarta    Data Analyst
1   Budi    Male   25  South Tangerang   Data Engineer
2   Caca  Female   30          Jakarta  Data Scientist
3   Dedi    Male   32          Bandung  Data Scientist
4  Erika  Female   28          Jakarta    Data Analyst
5  Fahri    Male   24         Surabaya   Data Engineer
6   Gina  Female   29          Bandung     ML Engineer
7   Hani  Female   31       Yogyakarta   ML Researcher
8   Irja    Male   30          Jakarta      BI Analyst
9  Jarot    Male   29  South Tangerang    Data Analyst

**Step 5. Add 1 new column named 'Hobby' and fill in the data as shown in the following output.**

In [13]:
df['Hobby'] = ['Gaming', 'Futsal', 'Read', 'Gaming', 'Cooking', 'Traveling', 'Basketball', 'Traveling', 'Gaming', 'Futsal']
df

    Name  Gender  Age         Domicile      Occupation       Hobby
0   Andi    Male   24          Jakarta    Data Analyst      Gaming
1   Budi    Male   25  South Tangerang   Data Engineer      Futsal
2   Caca  Female   30          Jakarta  Data Scientist        Read
3   Dedi    Male   32          Bandung  Data Scientist      Gaming
4  Erika  Female   28          Jakarta    Data Analyst     Cooking
5  Fahri    Male   24         Surabaya   Data Engineer   Traveling
6   Gina  Female   29          Bandung     ML Engineer  Basketball
7   Hani  Female   31       Yogyakarta   ML Researcher   Traveling
8   Irja    Male   30          Jakarta      BI Analyst      Gaming
9  Jarot    Male   29  South Tangerang    Data Analyst      Futsal

**6. Use .iloc to retrieve data for Dedi, Fahri, Hani**

In [14]:
df.iloc[3:8:2]

    Name  Gender  Age    Domicile      Occupation      Hobby
3   Dedi    Male   32     Bandung  Data Scientist     Gaming
5  Fahri    Male   24    Surabaya   Data Engineer  Traveling
7   Hani  Female   31  Yogyakarta   ML Researcher  Traveling

**7. Use .loc to display the domicile and occupation of Caca and Irja (including the name column)**

In [15]:
df.loc[[2,8],['Name', 'Domicile', 'Occupation']]

   Name Domicile      Occupation
2  Caca  Jakarta  Data Scientist
8  Irja  Jakarta      BI Analyst

**8. Gunakan .loc untuk menampilkan semua data dari Hani, Irja, Jarot**

In [16]:
df.loc[7:9]

    Name  Gender  Age         Domicile     Occupation      Hobby
7   Hani  Female   31       Yogyakarta  ML Researcher  Traveling
8   Irja    Male   30          Jakarta     BI Analyst     Gaming
9  Jarot    Male   29  South Tangerang   Data Analyst     Futsal

**9. Who is over 30 years old?**

In [17]:
df[df['Age']>30]

   Name  Gender  Age    Domicile      Occupation      Hobby
3  Dedi    Male   32     Bandung  Data Scientist     Gaming
7  Hani  Female   31  Yogyakarta   ML Researcher  Traveling

**10. Who is under 30 years old and whose hobby is gaming?**

In [19]:
df.loc[(df['Age']<30) & (df['Hobby']=='Gaming')]

   Name Gender  Age Domicile    Occupation   Hobby
0  Andi   Male   24  Jakarta  Data Analyst  Gaming

**11. Tampilkan nama orang yang pekerjaannya adalah Data Analyst! Tampilkan kolom nama saja dalam bentuk Series!**

In [22]:
df[df['Occupation']=='Data Analyst']['Name']

0     Andi
4    Erika
9    Jarot
Name: Name, dtype: object

**12. What are the jobs of people who live in Jakarta? Show their names and jobs!**

In [23]:
df.loc[
df['Domicile']=='Jakarta',
['Name', 'Occupation']
]

    Name      Occupation
0   Andi    Data Analyst
2   Caca  Data Scientist
4  Erika    Data Analyst
8   Irja      BI Analyst

**13. What are the hobbies of the women in the data? Show only the Name, Hobby, Age columns in order!**

In [24]:
df.loc[
df['Gender']=='Female',
['Name', 'Hobby', 'Age']
]

    Name       Hobby  Age
2   Caca        Read   30
4  Erika     Cooking   28
6   Gina  Basketball   29
7   Hani   Traveling   31

**14. Who is older than Erika? Show only the name column in DataFrame!**

In [25]:
df.loc[
df['Age']>df[df['Name']=='Erika']['Age'].values[0],
['Name']
]

    Name
2   Caca
3   Dedi
6   Gina
7   Hani
8   Irja
9  Jarot

**15. Based on the data, are there any women whose hobby is traveling?**

In [31]:
df[(df['Gender']=='Female') & (df['Hobby']=='Traveling')]

   Name  Gender  Age    Domicile     Occupation      Hobby
7  Hani  Female   31  Yogyakarta  ML Researcher  Traveling

In [33]:
# Loading dataset army
json_url = 'https://raw.githubusercontent.com/harishmuh/Data_Science_Bootcamp_Training/refs/heads/main/Purwadhika_DataScience_MachineLearning/Data_Analysis_With_Python_SQL_and_ETL/Datasets/army.json'
army = pd.read_csv(json_url)
army

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

**16. Create a dataframe from the json string below and save it into a variable named army.**

Json_string:
{
  "army_data": [
    {
      "regiment": "Nighthawks",
      "company": "1st",
      "deaths": 523,
      "battles": 5,
      "size": 1045,
      "veterans": 1,
      "readiness": 1,
      "armored": 1,
      "deserters": 4,
      "origin": "Arizona"
    },
    {
      "regiment": "Nighthawks",
      "company": "1st",
      "deaths": 52,
      "battles": 42,
      "size": 957,
      "veterans": 5,
      "readiness": 2,
      "armored": 0,
      "deserters": 24,
      "origin": "California"
    },
    {
      "regiment": "Nighthawks",
      "company": "2nd",
      "deaths": 25,
      "battles": 2,
      "size": 1099,
      "veterans": 62,
      "readiness": 3,
      "armored": 1,
      "deserters": 31,
      "origin": "Texas"
    },
    {
      "regiment": "Nighthawks",
      "company": "2nd",
      "deaths": 616,
      "battles": 2,
      "size": 1400,
      "veterans": 26,
      "readiness": 3,
      "armored": 1,
      "deserters": 2,
      "origin": "Florida"
    },
    {
      "regiment": "Dragoons",
      "company": "1st",
      "deaths": 43,
      "battles": 4,
      "size": 1592,
      "veterans": 73,
      "readiness": 2,
      "armored": 0,
      "deserters": 3,
      "origin": "Maine"
    },
    {
      "regiment": "Dragoons",
      "company": "1st",
      "deaths": 234,
      "battles": 7,
      "size": 1006,
      "veterans": 37,
      "readiness": 1,
      "armored": 1,
      "deserters": 4,
      "origin": "Iowa"
    },
    {
      "regiment": "Dragoons",
      "company": "2nd",
      "deaths": 523,
      "battles": 8,
      "size": 987,
      "veterans": 949,
      "readiness": 2,
      "armored": 0,
      "deserters": 24,
      "origin": "Alaska"
    },
    {
      "regiment": "Dragoons",
      "company": "2nd",
      "deaths": 62,
      "battles": 3,
      "size": 849,
      "veterans": 48,
      "readiness": 3,
      "armored": 1,
      "deserters": 31,
      "origin": "Washington"
    },
    {
      "regiment": "Scouts",
      "company": "1st",
      "deaths": 62,
      "battles": 4,
      "size": 973,
      "veterans": 48,
      "readiness": 2,
      "armored": 0,
      "deserters": 2,
      "origin": "Oregon"
    },
    {
      "regiment": "Scouts",
      "company": "1st",
      "deaths": 73,
      "battles": 7,
      "size": 1005,
      "veterans": 435,
      "readiness": 1,
      "armored": 0,
      "deserters": 3,
      "origin": "Wyoming"
    },
    {
      "regiment": "Scouts",
      "company": "2nd",
      "deaths": 37,
      "battles": 8,
      "size": 1099,
      "veterans": 63,
      "readiness": 2,
      "armored": 1,
      "deserters": 2,
      "origin": "Louisana"
    },
    {
      "regiment": "Scouts",
      "company": "2nd",
      "deaths": 35,
      "battles": 9,
      "size": 1523,
      "veterans": 345,
      "readiness": 3,
      "armored": 1,
      "deserters": 3,
      "origin": "Georgia"
    }
  ]
}

In [40]:
# Reading json file
import json

# Use json data file
json_data_string = """
{
  "army_data": [
    {
      "regiment": "Nighthawks",
      "company": "1st",
      "deaths": 523,
      "battles": 5,
      "size": 1045,
      "veterans": 1,
      "readiness": 1,
      "armored": 1,
      "deserters": 4,
      "origin": "Arizona"
    },
    {
      "regiment": "Nighthawks",
      "company": "1st",
      "deaths": 52,
      "battles": 42,
      "size": 957,
      "veterans": 5,
      "readiness": 2,
      "armored": 0,
      "deserters": 24,
      "origin": "California"
    },
    {
      "regiment": "Nighthawks",
      "company": "2nd",
      "deaths": 25,
      "battles": 2,
      "size": 1099,
      "veterans": 62,
      "readiness": 3,
      "armored": 1,
      "deserters": 31,
      "origin": "Texas"
    },
    {
      "regiment": "Nighthawks",
      "company": "2nd",
      "deaths": 616,
      "battles": 2,
      "size": 1400,
      "veterans": 26,
      "readiness": 3,
      "armored": 1,
      "deserters": 2,
      "origin": "Florida"
    },
    {
      "regiment": "Dragoons",
      "company": "1st",
      "deaths": 43,
      "battles": 4,
      "size": 1592,
      "veterans": 73,
      "readiness": 2,
      "armored": 0,
      "deserters": 3,
      "origin": "Maine"
    },
    {
      "regiment": "Dragoons",
      "company": "1st",
      "deaths": 234,
      "battles": 7,
      "size": 1006,
      "veterans": 37,
      "readiness": 1,
      "armored": 1,
      "deserters": 4,
      "origin": "Iowa"
    },
    {
      "regiment": "Dragoons",
      "company": "2nd",
      "deaths": 523,
      "battles": 8,
      "size": 987,
      "veterans": 949,
      "readiness": 2,
      "armored": 0,
      "deserters": 24,
      "origin": "Alaska"
    },
    {
      "regiment": "Dragoons",
      "company": "2nd",
      "deaths": 62,
      "battles": 3,
      "size": 849,
      "veterans": 48,
      "readiness": 3,
      "armored": 1,
      "deserters": 31,
      "origin": "Washington"
    },
    {
      "regiment": "Scouts",
      "company": "1st",
      "deaths": 62,
      "battles": 4,
      "size": 973,
      "veterans": 48,
      "readiness": 2,
      "armored": 0,
      "deserters": 2,
      "origin": "Oregon"
    },
    {
      "regiment": "Scouts",
      "company": "1st",
      "deaths": 73,
      "battles": 7,
      "size": 1005,
      "veterans": 435,
      "readiness": 1,
      "armored": 0,
      "deserters": 3,
      "origin": "Wyoming"
    },
    {
      "regiment": "Scouts",
      "company": "2nd",
      "deaths": 37,
      "battles": 8,
      "size": 1099,
      "veterans": 63,
      "readiness": 2,
      "armored": 1,
      "deserters": 2,
      "origin": "Louisana"
    },
    {
      "regiment": "Scouts",
      "company": "2nd",
      "deaths": 35,
      "battles": 9,
      "size": 1523,
      "veterans": 345,
      "readiness": 3,
      "armored": 1,
      "deserters": 3,
      "origin": "Georgia"
    }
  ]
}
"""

# If reading from a file:
# with open('your_file.json', 'r') as f:
#     data = json.load(f)

# If reading from a string:
data = json.loads(json_data_string)

# Extract the list associated with the "army_data" key
army = pd.DataFrame(data['army_data'])

army.head()

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine

**17. Make the 'origin' column the index of the dataframe**

In [41]:
army.set_index('origin', inplace=True)

In [42]:
army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

**18. Show only 'veterans' column**

In [43]:
army['veterans']

origin
Arizona         1
California      5
Texas          62
Florida        26
Maine          73
Iowa           37
Alaska        949
Washington     48
Oregon         48
Wyoming       435
Louisana       63
Georgia       345
Name: veterans, dtype: int64

**19. Show 'veterans' and 'deaths' columns**

In [44]:
army.loc[:, ['veterans', 'deaths']]

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43
Iowa              37     234
Alaska           949     523
Washington        48      62
Oregon            48      62
Wyoming          435      73
Louisana          63      37
Georgia          345      35

In [45]:
army[['veterans', 'deaths']]

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43
Iowa              37     234
Alaska           949     523
Washington        48      62
Oregon            48      62
Wyoming          435      73
Louisana          63      37
Georgia          345      35

**20. Show all column names**

In [46]:
army.columns

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters'],
      dtype='object')

**21. Show 'deaths', 'size' and 'deserters' columns originating from Maine and Alaska**

In [47]:
army.loc[
    ['Maine', 'Alaska'],
    ['deaths', 'size', 'deserters']
]

        deaths  size  deserters
origin
Maine       43  1592          3
Alaska     523   987         24

**22. Show rows 3 to 7 and columns 3 to 6**

In [48]:
army.iloc[2:7, 2:6]

         deaths  battles  size  veterans
origin
Texas        25        2  1099        62
Florida     616        2  1400        26
Maine        43        4  1592        73
Iowa        234        7  1006        37
Alaska      523        8   987       949

In [49]:
army.loc['Texas':'Alaska', 'deaths':'veterans']

         deaths  battles  size  veterans
origin
Texas        25        2  1099        62
Florida     616        2  1400        26
Maine        43        4  1592        73
Iowa        234        7  1006        37
Alaska      523        8   987       949

**23. Show all rows after the 4th row and all columns**

In [50]:
army.iloc[4:, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

**24. Show all rows up to row 4 and all columns**

In [51]:
army.iloc[:4, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2

**25. Show 3rd column to 7th column**

In [52]:
army.iloc[:, 2:7]

            deaths  battles  size  veterans  readiness
origin
Arizona        523        5  1045         1          1
California      52       42   957         5          2
Texas           25        2  1099        62          3
Florida        616        2  1400        26          3
Maine           43        4  1592        73          2
Iowa           234        7  1006        37          1
Alaska         523        8   987       949          2
Washington      62        3   849        48          3
Oregon          62        4   973        48          2
Wyoming         73        7  1005       435          1
Louisana        37        8  1099        63          2
Georgia         35        9  1523       345          3

**26a. Show rows where 'deaths' is greater than 50**

In [53]:
army[army['deaths']>50]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3

**26b. Show rows where 'deaths' is greater than 500 or less than 50**

In [54]:
army[(army['deaths']>500) | (army['deaths']<50)]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

**27. Show all regiments except "Dragoons"**

In [55]:
army[~(army['regiment']=='Dragoons')]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

**28. Select lines with Texas and Arizona origins**

In [56]:
army.loc[['Texas', 'Arizona']]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4

**29. Select the third cell in the row named Arizona**

In [57]:
army.loc[
    ['Arizona'],
    'deaths'
]

origin
Arizona    523
Name: deaths, dtype: int64

**30. Select the third cell from the column named 'deaths'**

In [58]:
army.iloc[[2], 2]

origin
Texas    25
Name: deaths, dtype: int64