## ETL Cleaning Data From SQL Database to Google BigQuery & Spreadsheets

#### Data Source ERD (Entity Relationship Diagram)

![TransactionsDB.png](https://github.com/harishmuh/Python-for-Data-Science-Analysis/blob/main/Assets/Transactions_pwdk_DB.png?raw=true)

[Source](https://dbdiagram.io/d/Transactions-671081c597a66db9a344b2c7)

#### Looker Dashboard Output Example

https://lookerstudio.google.com/u/0/reporting/510f0bd7-265b-400d-9fd4-333a40738dfe/page/21hHE

## **Summary**
### Data Source
1. **SQL Database**: Dummy Database from Purwadhika

### Workflow

#### 1. Retrieving Data
**Data Source:**
- **SQL Database**: SQL queries are used to combine transaction and survey data from relational tables.
- **Query**: Retrieves information related to transactions (`transact_code`), programs (`program_name`, `program_category`), users (`user_email`, `referral_source`), and surveys (`choosing_reason`, `registration_reason`, `other_bootcamps`).

#### 2. Filtering and Transformation

- **Time Column Data**: Make sure to convert to datetime and format it to GMT +7 (WIB), as the database value is always UTC 0.
- **Transaction Status**: Only successful transactions.

- **Study Method**: Only requires Online and On-Campus.
- **Referral**: Recategorize according to the Referral form (How did you first learn about Purwadhika?) found when a user first registers on the Purwadhika website.
- **User City**: Ensure all city names are used or they are considered overseas.

**Adding new columns for analysis**:
- Adding a `student_age` column to indicate the age of the registered student.

#### 3. Separating Survey Data into a Separate Worksheet/Table (not used in the Looker Dashboard)
**Reason for Separation:**
- **choosing_reason**: Stores the participant's reason for choosing the program.
- **registration_reason**: Stores the participant's reason for registering.
- **other_bootcamps**: Stores a history of other bootcamps the participant has attended.

The goal is to simplify distribution analysis, as the initial values ​​are only separated by commas and to prevent the survey data from being mixed with the main transaction data.

#### 4. Validation and Output
**Steps:**
- Ensure there are no anomalies or null values ​​in the cleaned data.
- Save the results to:
- **CSV file**: As a local backup.
- **Google Sheets**: Divided into worksheets based on data categories. (not used currently)
- **BigQuery**: For large-scale analysis on the Google Cloud platform. (data source for the Looker Dashboard)

### Preparation Before Running

#### 1. Create a JSON API Key for Google Cloud
**Steps to create a JSON API Key for Google Sheets and BigQuery:**
1. Log in to the Google Cloud Console.
2. Select or create a new project.
3. Enable the Google Sheets API and BigQuery API.
4. Go to **Credentials** > **Create Credentials** > **Service Account**.
5. Enter the service account name, select the **Editor** role for Google Sheets and **BigQuery Admin** for BigQuery.
6. Create and download a JSON key, then save it in your repository's root directory (example: `google_api_key.json`).

#### 2. Notebook Configuration
- Make sure the JSON file is in the root folder.
- Add the JSON file path to the notebook:

```python
api_key_path = 'google_api_key.json'

- However, in this notebook, we don't use a JSON file; instead, we store the credentials directly in the notebook (in the "credentials_info" variable).

#### Import Libraries

In [ ]:
#!pip install sqlalchemy
#!pip install pymysql

In [1]:
import pandas as pd
from sqlalchemy import create_engine
import warnings

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 2000)
pd.set_option('display.width', 1000)
pd.set_option('max_colwidth', 500)
warnings.filterwarnings("ignore", category=FutureWarning)

In [ ]:
# Database connection
db_user = 'root'
db_password = 'yourMYSQLPassword'  # Replace with your MySQL root password
db_host = 'localhost'
db_port = '3306'
db_name = 'dummypwdkdb_jcdsoll2'  # Database name

# Create the engine
engine = create_engine(f'mysql+pymysql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

#### **Getting Transactions, Programs, Branches, Students, etc from MySQL Database**

   First, please view and understand the data structure at https://dbdiagram.io/d/Transactions-671081c597a66db9a344b2c7 to better understand the query.

In [3]:
# Query to fetch data from the database
query = '''
SELECT
    t.code AS transact_code,
    t.invoice_created_at,
    t.created_at AS transaction_created_date,
    t.user_code,
    t.subtotal_amount,
    t.total_discount_amount,
    t.final_price,
    t.receivable_amount,
    t.created_by,
    t.invoice_code,
    t.order_confirmation_code,

    pt.quantity,
    ts.label AS transaction_status,
    ph.label AS program_name,
    b.label AS branch_name,
    pc.label AS program_category,
    sm.label AS study_method,
    ss.label AS study_schedule,

    p.program_start_date,
    p.program_end_date,
    p.program_start_time,
    p.program_end_time,
    p.program_days,

    u.referral_source,
    u.user_email,
    u.user_city,
    u.birth_date,

    tq.registration_reason,
    tq.time_knowing_program,
    tq.choosing_reason,
    tq.content_source,
    tq.other_bootcamps,
    tq.first_time_knowledge,
    tq.informative_website,
    tq.admission_score

FROM transact t
LEFT JOIN transactstatus ts ON ts.code = t.transaction_status_code
LEFT JOIN programtransact pt ON t.code = pt.transaction_code
LEFT JOIN program p ON p.code = pt.program_code
LEFT JOIN branch b ON b.code = p.branch_code
LEFT JOIN programheader ph ON ph.code = p.program_header_code
LEFT JOIN programcategory pc ON pc.code = ph.program_category_code
LEFT JOIN studymethod sm ON sm.code = p.study_method_code
LEFT JOIN studyschedule ss ON ss.code = p.study_schedule_code
LEFT JOIN student s ON pt.code = s.program_transact_code
LEFT JOIN user u ON u.code = s.user_code
LEFT JOIN transactquestionnaires tq ON t.code = tq.code
'''

# Execute query and load into a pandas DataFrame
df = pd.read_sql(query, engine)

#### **Data Cleaning**

In [4]:
# Data from SQL by default is always in UTC 00:00 format
# Set to UTC
df['transaction_created_date'] = pd.to_datetime(df['transaction_created_date']).dt.tz_localize('Etc/GMT+0')
df['invoice_created_at'] = pd.to_datetime(df['invoice_created_at']).dt.tz_localize('Etc/GMT+0')
# Convert ke GMT+7
df['transaction_created_date'] = df['transaction_created_date'].dt.tz_convert('Etc/GMT-7')
df['invoice_created_at'] = df['invoice_created_at'].dt.tz_convert('Etc/GMT-7')

In [5]:
df.sample()

     transact_code        invoice_created_at  transaction_created_date  user_code  subtotal_amount  total_discount_amount  final_price  receivable_amount  created_by         invoice_code order_confirmation_code  quantity transaction_status                                  program_name              branch_name program_category study_method      study_schedule  program_start_date    program_end_date program_start_time program_end_time program_days referral_source          user_email user_city    birth_date                                                                                                             registration_reason time_knowing_program                                                                                                     choosing_reason content_source  other_bootcamps first_time_knowledge informative_website admission_score
618          15585 2024-08-26 17:20:22+07:00 2024-08-26 15:40:43+07:00      37677         30000000                6000000     24000000                  0  admission7  INV/2024/08/26/0028      ON/2024/08/26/0026         1               Paid  Job Connector Bootcamp Visual & UI/UX Design  Purwadhika Campus Jogja    Job Connector    On Campus  Full Time Training 2024-09-29 17:00:00 2025-01-21 17:00:00              09:00            12:00      Mon-Fri   Google search  users611@gmail.com  Semarang  13/July/2004  Kebutuhan untuk segera mendapatkan pekerjaan,Dana belajar yang akhirnya sudah terkumpul,Karena promo yang akan segera berakhir    6 bulan - 1 tahun  Jadwal Intake yang sesuai kebutuhan,Kredibilitas Purwadhika sejak tahun 1987,Lokasi tidak jauh dari tempat tinggal        Youtube  Revou, hacktiv8                 None         Sangat Baik            Baik

In [6]:
df.sample()

,transact_code,invoice_created_at,transaction_created_date,user_code,subtotal_amount,total_discount_amount,final_price,receivable_amount,created_by,invoice_code,order_confirmation_code,quantity,transaction_status,program_name,branch_name,program_category,study_method,study_schedule,program_start_date,program_end_date,program_start_time,program_end_time,program_days,referral_source,user_email,user_city,birth_date,registration_reason,time_knowing_program,choosing_reason,content_source,other_bootcamps,first_time_knowledge,informative_website,admission_score
399,12453,2024-01-22 17:22:22+07:00,2024-01-22 16:27:47+07:00,28174,47175000,9175000,38000000,0,admission3,INV/2024/01/22/0027,ON/2024/01/22/0040,1,Paid,Job Connector Bootcamp Digital Marketing,Purwadhika Campus Jakarta,Job Connector,On Campus,Full Time Training,2024-02-25 17:00:00,2024-06-10 17:00:00,09:00,16:00,Mon - Fri,Linkedin Purwadhika,users233@gmail.com,Surakarta,8/August/1998,"Kebutuhan untuk segera mendapatkan pekerjaan,Sudah yakin untuk career switch dengan dibantu purwadhika",1 Minggu - 1 Bulan,"Fasilitas kampus Purwadhika,Rekomendasi dari seseorang,Biaya pendidikan Purwadhika,Jadwal Intake yang sesuai kebutuhan,Kredibilitas Purwadhika sejak tahun 1987,Promo yang sedang berjalan,Kisah sukses dari para Alumni Purwadhika,Materi/Silabus/Kurikulum Purwadhika",Facebook,id/x partners,Hanya mengetahui Purwadhika,Sangat Baik,Sangat Baik

##### **Data Filter only Successful transactions**

In [7]:
df = df[df['transaction_status'] == 'Paid']

##### **Re-categorize Referrals according to the options available when registering as a user (can be seen on the Purwadhika website when registering)**

In [8]:
referral_opsi_website = ['Google Search','Friends/Family','Instagram Ads','Social Media Purwadhika','News Coverage','Blog Purwadhika','Social Media Influencer']

In [9]:
# inappropriate / other referrals
df[~df['referral_source'].isin(referral_opsi_website)]['referral_source'].unique()

array(['Youtube Purwadhika', 'chat-GPT', 'teman',
       'Instagram Purwadhika (non ads)', 'Podcast Cukup Menarik',
       'Friends / Family Referral', 'Sudah lama dari instagram',
       'Media Coverage', 'Youtube Non Ads', 'youtube', 'Youtube Ads',
       'Media sosial dan forum online', 'Instagram Non Ads', 'Orang tua',
       'Student & Alumni Referral', 'Instagram Purwadhika',
       'LinkedIn Purwadhika', 'Teman',
       'Sudah lama, pernah mengikuti workshop', 'Linkedin Purwadhika',
       'Family', 'Dari teman',
       'Pernah membaca sebuah tweet salah satu alumni purwadhika',
       'Teman ', 'Keluarga', 'Instagram ', 'Kerabat', 'Google search',
       None, 'Student/Alumni Purwadhika referral', 'Saudara',
       'Teman Orang Tua', 'Alumni/Student Purwadhika',
       'Browsing internet', 'Twitter Purwadhika', 'Tik Tok Ads',
       'Friends/Family referral', 'Teman saya'], dtype=object)

In [10]:
# Mapping dictionary
referral_mapping = {
    'Friends / Family Referral': 'Friends/Family',
    'Teman': 'Friends/Family',
    'teman': 'Friends/Family',
    'Teman Orang Tua': 'Friends/Family',
    'Teman sekolah': 'Friends/Family',
    'Teman saya': 'Friends/Family',
    'Dari teman kakak': 'Friends/Family',
    'Saudara': 'Friends/Family',
    'Keluarga': 'Friends/Family',
    'Dari Orang Terdekat': 'Friends/Family',
    'Keponakan saya memberitahukan saya tentang Purwadika': 'Friends/Family',
    'Instagram Purwadhika': 'Social Media Purwadhika',
    'Instagram Non Ads': 'Social Media Purwadhika',
    'Instagram Purwadhika (non ads)': 'Social Media Purwadhika',
    'Youtube Purwadhika': 'Social Media Purwadhika',
    'Youtube Non Ads': 'Social Media Purwadhika',
    'Youtube Ads': 'Social Media Purwadhika',
    'youtube': 'Social Media Purwadhika',
    'Tik Tok Non Ads': 'Social Media Influencer',
    'Tik Tok Ads': 'Social Media Influencer',
    'LinkedIn Purwadhika': 'Social Media Purwadhika',
    'Linkedin Purwadhika': 'Social Media Purwadhika',
    'Facebook Page Purwadhika': 'Social Media Purwadhika',
    'Twitter Purwadhika': 'Social Media Purwadhika',
    'Berita': 'News Coverage',
    'Media Coverage': 'News Coverage',
    'Searching': 'Google Search',
    'Google Search': 'Google Search'
}

# Apply the mapping
df['referral_source'] = df['referral_source'].replace(referral_mapping)


# Replace any values not in referral_opsi_website with 'Other'
df['referral_source'] = df['referral_source'].apply(lambda x: x if x in referral_opsi_website else 'Other')

# Important Note:
# When analyzing referral sources, values can be grouped into specific categories to simplify the interpretation and reporting of the data.
# The following categories can be useful for various purposes such as marketing analysis, campaign effectiveness, or user behavior tracking

##### **Study Method is Simply Online & On Campus**

In [11]:
method_mapping = {
'Livestream Class': 'Online',
'Video Learning':'Online' }
df['study_method'] = df['study_method'].replace(referral_mapping)

##### **User City**

User City data needs to be cleaned to ensure that the recorded values ​​represent valid city names,
especially for users outside of Indonesia. Users from abroad are recorded using country names, not city names.

In [12]:
# List of country names (you can add more as needed)
countries = ['Turkey', 'Switzerland', 'Malaysia', 'Japan', 'Australia']

# Function to clean city names by checking if it's a country
def clean_user_city(city):
    if city in countries:
        return 'Luar Negeri'  # Replace country name with "Luar Negeri"
    elif city is None or city == '':
        return 'Tidak Diketahui'  # Handle None or empty strings
    else:
        return city  # Leave city names unchanged

# Apply the cleaning function to the 'user_city' column
df['user_city'] = df['user_city'].apply(clean_user_city)

# Check the updated column
df['user_city'].unique()

array(['Jambi', 'Batam', 'Denpasar', 'Medan', 'Badung', 'Banjar',
       'Bandung', 'Bandar Lampung', 'Tegal', 'Pekalongan', 'Semarang',
       'Jakarta Utara', 'Singkawang', 'Jakarta Pusat',
       'Tangerang Selatan', 'Manado', 'Banda Aceh', 'Jakarta Barat',
       'Bekasi', 'Majalengka', 'Tangerang', 'Kediri', 'Bengkulu',
       'Blitar', 'Purwokerto', 'Magelang', 'Malang', 'Bontang',
       'Banyumas', 'Ambon', 'Banjarmasing', 'Sleman', 'Wonosobo', 'Depok',
       'Mataram', 'Bima', 'Payakumbuh', 'Purbalingga', 'Tidak Diketahui',
       'Surakarta', 'Tanjungpinang', 'Binjai', 'Samarinda', 'Padang',
       'Jakarta Raya', 'Surabaya', 'Pekanbaru', 'Makassar', 'Luar Negeri',
       'Pematangsiantar', 'Yogyakarta', 'Tasikmalaya', 'Banjarbaru',
       'Palembang', 'Pontianak', 'Cirebon', 'Balikpapan',
       'Jakarta Selatan', 'Bogor', 'Jakarta Timur', 'Badung (Bali)',
       'Sukabumi', 'Cilegon', 'Cimahi'], dtype=object)

### **Student Age**

In [13]:
# Dictionary to map Indonesian months to English
month_translation = {
    'Januari': 'January', 'Februari': 'February', 'Maret': 'March', 'April': 'April',
    'Mei': 'May', 'Juni': 'June', 'Juli': 'July', 'Agustus': 'August',
    'September': 'September', 'Oktober': 'October', 'November': 'November', 'Desember': 'December'
}

# Replace Indonesian month names with English month names
for indo_month, eng_month in month_translation.items():
    df['birth_date'] = df['birth_date'].str.replace(indo_month, eng_month)

# Convert program_start_date to datetime
df['program_start_date'] = pd.to_datetime(df['program_start_date'])

# Convert birth_date to datetime without strict format to handle mixed month names
df['birth_date'] = pd.to_datetime(df['birth_date'], errors='coerce')

# Calculate age in years
df['student_age'] = (df['program_start_date'] - df['birth_date']).dt.days // 365

#### **Transaction Surveys (Bahasa Indonesia & English)**

---

### 1. Apa yang mendorong Anda untuk mendaftar Purwadhika sekarang?  
*(Multiple choice - `registration_reason`)*  
**What motivates you to register at Purwadhika now?**  
- Karena promo yang akan segera berakhir  
  *Because of a promotion that will end soon*  
- Dana belajar yang akhirnya sudah terkumpul  
  *Learning funds have finally been collected*  
- Waktu belajar yang akhirnya tersedia  
  *Study time has finally become available*  
- Kebutuhan untuk segera mendapatkan pekerjaan  
  *The need to get a job immediately*  
- Perintah atau diutus oleh Perusahaan  
  *Sent or instructed by the company*  
- Perintah dari Orang Tua/Keluarga  
  *Instruction from parents/family*  
- Tergerak karena promo yang menarik  
  *Motivated by an attractive promotion*  
- Alasan Lainnya (Diisi sendiri)  
  *Other reasons (self-written)*  

---

### 2. Berapa lama Anda sudah mengetahui Purwadhika?  
*(Single choice - `time_knowing_program`)*  
**How long have you known about Purwadhika?**  
- 1 Hari - 1 Minggu  
  *1 Day - 1 Week*  
- 1 Minggu - 1 Bulan  
  *1 Week - 1 Month*  
- 1 - 3 Bulan  
  *1 - 3 Months*  
- 3 - 6 Bulan  
  *3 - 6 Months*  
- 6 Bulan - 1 Tahun  
  *6 Months - 1 Year*  
- '>1 Tahun'  
  *More than 1 Year*  

---

### 3. Kenapa memilih Purwadhika dibanding bootcamp lain?  
*(Multiple choice - `choosing_reason`)*  
**Why did you choose Purwadhika over other bootcamps?**  
- Hanya mengetahui Purwadhika  
  *Only know Purwadhika*  
- Kredibilitas Purwadhika sejak tahun 1987  
  *Purwadhika’s credibility since 1987*  
- Promo yang sedang berjalan  
  *Ongoing promotion*  
- Fasilitas kampus Purwadhika  
  *Purwadhika’s campus facilities*  
- Kisah sukses dari para Alumni Purwadhika  
  *Success stories from Purwadhika alumni*  
- Pengajar dan Mentor Purwadhika  
  *Purwadhika instructors and mentors*  
- Materi/Silabus/Kurikulum Purwadhika  
  *Purwadhika’s learning materials/syllabus/curriculum*  
- Rekomendasi dari seseorang  
  *Recommendation from someone*  
- Pilihan dari Perusahaan  
  *Company’s decision*  
- Biaya pendidikan Purwadhika  
  *Purwadhika’s tuition fee*  
- Jadwal Intake yang sesuai kebutuhan  
  *Intake schedule that fits needs*  
- Alasan Lainnya (Diisi sendiri)  
  *Other reasons (self-written)*  

---

### 4. Pilih media sosial Purwadhika yang paling mempengaruhi Anda melakukan transaksi  
*(Single choice - `content_source`)*  
**Choose the Purwadhika social media that most influenced your decision to register**  
- Instagram  
- Youtube  
- Twitter / (X)  
- Facebook  
- LinkedIn  
- Tidak Ada  
  *None*  

---

### 5. Masukkan nama-nama tempat bootcamp lain yang Anda ketahui  
*(Free text - `other_bootcamps`)*  
**Enter the names of other bootcamps you know**  
- Jika lebih dari satu, pisahkan dengan koma.  
  *If more than one, separate with commas.*  

---

### 6. Apakah Purwadhika adalah tempat bootcamp pertama yang Anda ketahui?  
*(Single choice - `first_time_knowledge`)*  
**Is Purwadhika the first bootcamp you’ve ever heard of?**  
- Ya  
  *Yes*  
- Tidak  
  *No*  
- Hanya mengetahui Purwadhika  
  *Only know Purwadhika*  

---

### 7. Apakah website kami memudahkan Anda dalam memperoleh informasi yang diperlukan sebelum mendaftar di Purwadhika?  
*(Single choice - `informative_website`)*  
**Does our website make it easy for you to get the information you need before registering at Purwadhika?**  
- Sangat Buruk  
  *Very Poor*  
- Buruk  
  *Poor*  
- Memadai  
  *Adequate*  
- Baik  
  *Good*  
- Sangat Baik  
  *Very Good*  

---

### 8. Bagaimana penilaian Anda terhadap pelayanan dari Tim Admission kami?  
*(Single choice - `admission_score`)*  
**How would you rate the service from our Admission Team?**  
- Sangat Buruk  
  *Very Poor*  
- Buruk  
  *Poor*  
- Memadai  
  *Adequate*  
- Baik  
  *Good*  
- Sangat Baik  
  *Very Good*

#### **registration_reason, choosing_reason, other_bootcamps (multiple choice columns)**

It is necessary to create a separate table with values ​​without commas so that calculations are easy to do.

##### **registration_reason**

In [14]:
listData = []
for item in df[['registration_reason', 'transact_code']].values:
    trxId = item[1]
    if item[0] is not None:  # Check if the value is not None
        if ',' in item[0]:
            my_list = item[0].split(',')
            for value_list in my_list:
                listData.append([value_list.strip(), trxId])  # strip() to remove any extra spaces
        else:
            listData.append([item[0].strip(), trxId])
    else:
        listData.append([None, trxId])  # Handle None values as well

registration_reason_dataframe = pd.DataFrame(columns=['registration_reason','transact_code'], data=listData)

In [15]:
registration_reason_dataframe.head(2)

                      registration_reason  transact_code
0  Karena promo yang akan segera berakhir           9343
1    Waktu belajar yang akhirnya tersedia           9343

In [17]:
# Pisah kan jawaban yang diluar template website, dan categori ulang
# Separate answers that are outside the website template, and recategorize them.
reason_list = [
    "Karena promo yang akan segera berakhir",   # Because of a promotion that will end soon
    "Dana belajar yang akhirnya sudah terkumpul",   # Learning funds have finally been collected
    "Waktu belajar yang akhirnya tersedia",   # Study time has finally become available
    "Kebutuhan untuk segera mendapatkan pekerjaan",   # The need to get a job immediately
    "Perintah atau diutus oleh Perusahaan",   # Sent or instructed by the company
    "Perintah dari Orang Tua/Keluarga",   # Instruction from parents/family
    "Tergerak karena promo yang menarik"   # Motivated by an attractive promotion
]

# List yang tidak sesuai silahkan jika ada jawaban yang mirip atau sama dengan list yang sesuai template website agar diubah sesuaii template website,jika tidak bisa cukup sebagai Other atau membuat categori baru
# If the list does not match, please change the answer that is similar or the same as the list that matches the website template to match the website template. 
# If this is not possible, simply categorize it as Other or create a new category.
registration_reason_dataframe[~registration_reason_dataframe['registration_reason'].isin(reason_list)]['registration_reason'].unique()

array(['mencari pengalaman baru',
       'Untuk mendapat ilmu serta mentor yang bisa membimbing saya.',
       'ingin memulai karir di bidang baru yang lebih berpotensi yang nantinya bisa menyokong dana untuk plan selanjutnya',
       'Menambah ilmu dan persiapan untuk masuk ke dunia kerja',
       'Belajar data analyst',
       'Image Bagus dan menciptakan alumni terbaik',
       'Tertarik dan ingin belajar dalam bidang IT Pemrograman',
       'Karena adanya program job conector', 'switcing  karir',
       'perlu mengembangkan skill digital marketing',
       'Ingin upgrade diri terkait skill digitalisasi', 'menambah skill',
       'Ingin mempelajari hal lain dan hal baru selain pelajaran S1',
       'Saya mau switch career',
       'untuk menambah pengalaman dan menambah skill',
       'Ingin memulai berbisnis dan membutuhkan skill tertentu',
       'Mengembangankan usaha',
       'Karena ingin mendapatkan ilmu baru yang dapat menunjang karir',
       '-', 'menambah keterampilam dan wawasan di bidang ilmu digital',
       'kebutuhan segera belajar untuk mengembangkan usaha',
       'Rekomendasi dari Orang Tua', 'Ingin segera mahir',
       'tertarik dengan materi course', 'Ingin switch career',
       'Ingin belajar hal baru',
       'Kebutuhan untuk belajar memahami data analytics',
       'Switch career to digital marketing', 'Menambah skill',
       'Ingin mendapatkan ilmu yang baru', 'Switch karir',
       'Kebutuhan untuk skill upgrade',
       'Ingin memiliki skill dan kesempatan career yang lebih luas',
       'rekomendasi dari orangtua saya',
       'Materi pembelajaran job connector', 'Referensi/inspirasi skripsi',
       'Ingin memiliki skills tambahan untuk mendukung pekerjaan saat ini',
       'Menambah pengetahuan dan skill',
       'Karna saya butuh mempelajari visual design dari awal',
       'Untuk menjadi profesional',
       'Materi ilmu yang dapat bermanfaat dikemudian hari',
       'Ingin belajar lebih banyak tentang digital marketing',
       'Upgrade skills', 'ingin mempelajari lebih dalam dan lebih jelas',
       'Ingin memiliki skill digital', 'INGIN MEMPERDALAM SKILL',
       'Passion belajar Data Science',
       'Sudah yakin untuk career switch dengan dibantu purwadhika',
       'Ingin mengetahui terkait data science',
       'Ingin mengembangkan diri di bidang data scientist dan mendapat pekerjaan di role tersebut',
       'ingin sekali mendalami ilmu digital di era yg serba digital',
       'Menambah ilmu untuk mendapat pekerjaan yg diinginkan',
       'tertarik untuk mempelajari hal baru dan mencoba untuk membuka peluang baru',
       'Karna mau dari diri saya sendiri', 'Ketertarikan di UI UX',
       'Keinginan untuk belajar digital marketing',
       'Mendalami digital marketing',
       'ingin belajar kembali bidang desain visual', 'adding more skill',
       'Sudah ada waktu', 'Upgrade skill untuk menamgah pemasukan',
       'Kebutuhan belajar',
       'Upgrade skill before continuing my master degree',
       'Menyiapkan diri untuk perkembangan digital di masa depan.',
       'i want to add as much knowledge to my tech stack',
       'On campus/ Offline', 'Ingin menambah skill',
       'Waktu yang tepat meningkatkan skill'], dtype=object)

##### **choosing_reason**

In [18]:
listData = []
for item in df[['choosing_reason', 'transact_code']].values:
    trxId = item[1]
    if item[0] is not None:  # Check if the value is not None
        if ',' in item[0]:
            my_list = item[0].split(',')
            for value_list in my_list:
                listData.append([value_list.strip(), trxId])  # strip() to remove any extra spaces
        else:
            listData.append([item[0].strip(), trxId])
    else:
        listData.append([None, trxId])  # Handle None values as well

choosing_reason_dataframe = pd.DataFrame(columns=['choosing_reason','transact_code'], data=listData)

In [19]:
choosing_reason_dataframe.head(2)

                            choosing_reason  transact_code
0  Kredibilitas Purwadhika sejak tahun 1987           9343
1  Kisah sukses dari para Alumni Purwadhika           9343

In [20]:
# Pisah kan jawaban yang diluar template website, dan categori ulang
# Separate answers that are outside the website template, and recategorize them.
choosing_reason_list = [
    "Hanya mengetahui Purwadhika",   # Only know Purwadhika
    "Kredibilitas Purwadhika sejak tahun 1987",   # Purwadhika’s credibility since 1987
    "Promo yang sedang berjalan",   # Ongoing promotion
    "Fasilitas kampus Purwadhika",   # Purwadhika’s campus facilities
    "Kisah sukses dari para Alumni Purwadhika",   # Success stories from Purwadhika alumni
    "Pengajar dan Mentor Purwadhika",   # Purwadhika instructors and mentors
    "Materi/Silabus/Kurikulum Purwadhika",   # Purwadhika’s learning materials/syllabus/curriculum
    "Rekomendasi dari seseorang",   # Recommendation from someone
    "Pilihan dari Perusahaan",   # Company’s decision
    "Biaya pendidikan Purwadhika",   # Purwadhika’s tuition fee
    "Jadwal Intake yang sesuai kebutuhan"   # Intake schedule that fits needs
]

# List yang tidak sesuai silahkan jika ada jawaban yang mirip atau sama dengan list yang sesuai template website agar diubah sesuaii template website,jika tidak bisa cukup sebagai Other atau membuat categori baru
# If the list does not match, please change the answer that is similar or the same as the list that matches the website template to match the website template. 
# If this is not possible, simply categorize it as Other or create a new category.
choosing_reason_dataframe[~choosing_reason_dataframe['choosing_reason'].isin(choosing_reason_list)]['choosing_reason'].unique()

array(['Kelas tatap muka', '', 'Keren',
       'saya membutuhkan bootcamp oppline/ on campus', 'karna on site',
       'Metode pembelajaran offline', 'fasilitas job connector nya',
       'Bisa Offline di Bandung', 'Ada on campus di kota saya tinggal',
       'yakni jogja', 'On campus/ Offline', 'Daerah Jogja',
       'pernah ikut Purwadhika sebelumnya', 'Ada di Jogja',
       'dekat dengan domisili saya yang di Surakarta.',
       'Suka dengan purwadhika detail informasinya dan dari dulu pas awal tahu pengen banget ikut kelas purwadhika',
       'Fasilitas alumni bootcamp untuk mendapatkan koneksi untuk  pekerjaan',
       'interactive onlie', 'Teman yang sudah pernah berada di dalamnya',
       'kelas offline', 'Ada kampus on site',
       'mudah dijangkau dari rumah',
       'relatif dekat dengan tempat tinggal',
       'Jadwal cocok dan dekat dg tmpt kerja',
       'Ingin mendapatkan pekerjaan secepatnya karena fasilitas job connect',
       'jarak', 'Purwadhika memiliki fasilitas belajar on campus',
       'lebih khusus di Jogja.', 'job connector', 'rekomendasi dari kaka',
       'Lokasi tidak jauh dari tempat tinggal',
       'Purwadhika memiliki offline class', 'Program job connector'],
      dtype=object)

##### **other_bootcamps**

In [21]:
listData = []
for item in df[['other_bootcamps', 'transact_code']].values:
    trxId = item[1]
    if item[0] is not None:  # Check if the value is not None
        if ',' in item[0]:
            my_list = item[0].split(',')
            for value_list in my_list:
                listData.append([value_list.strip(), trxId])  # strip() to remove any extra spaces
        else:
            listData.append([item[0].strip(), trxId])
    else:
        listData.append([None, trxId])  # Handle None values as well

# Create the new DataFrame
other_bootcamps_dataframe = pd.DataFrame(columns=['other_bootcamps', 'transact_code'], data=listData)

In [22]:
other_bootcamps_dataframe.head()

  other_bootcamps  transact_code
0        Hacktiv8           9343
1    binaracademy           9343
2    dibimbing.id           9343
3           RevoU           9358
4        Hacktiv8           9358

In [23]:
# Normalize the 'other_bootcamps' column
other_bootcamps_dataframe['other_bootcamps'] = (
    other_bootcamps_dataframe['other_bootcamps']
    .str.strip()  # Remove leading and trailing spaces
    .str.replace(r'\s+', ' ', regex=True)  # Replace multiple spaces with a single space
    .str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)  # Remove non-alphabetic and non-numeric characters
    .str.lower()
)

In [ ]:
other_bootcamps_dataframe['grouped_bootcamps'] = other_bootcamps_dataframe['other_bootcamps']

other_bootcamps_dataframe.loc[(other_bootcamps_dataframe['other_bootcamps'].str.startswith('hac')) |
                          (other_bootcamps_dataframe['other_bootcamps'].str.startswith('hak')) |
                          (other_bootcamps_dataframe['other_bootcamps'].str.startswith('heac'))|
                          (other_bootcamps_dataframe['other_bootcamps'].str.startswith('h8')) |
                          (other_bootcamps_dataframe['other_bootcamps'] == ' hcktiv8')
                          , 'grouped_bootcamps'] = 'Hacktiv8'
other_bootcamps_dataframe.loc[(other_bootcamps_dataframe['other_bootcamps'].str.startswith('rev',na=False)), 'grouped_bootcamps'] = 'RevoU'
other_bootcamps_dataframe.loc[(other_bootcamps_dataframe['other_bootcamps'].str.startswith('my',na=False)) & (other_bootcamps_dataframe['other_bootcamps'].str.contains('skil',na=False))
                              , 'grouped_bootcamps'] = 'MySkill'
other_bootcamps_dataframe.loc[(other_bootcamps_dataframe['other_bootcamps'].str.contains('senin',na=False))
                          , 'grouped_bootcamps'] = 'Hari Senin'
other_bootcamps_dataframe.loc[(other_bootcamps_dataframe['other_bootcamps'].str.contains('binar',na=False))
                          , 'grouped_bootcamps'] = 'Binar Academy'
other_bootcamps_dataframe.loc[(other_bootcamps_dataframe['other_bootcamps'].str.contains('bimbing',na=False))
                          , 'grouped_bootcamps'] = 'Dibimbing'
other_bootcamps_dataframe.loc[(other_bootcamps_dataframe['other_bootcamps'].str.contains('raka',na=False))
                          , 'grouped_bootcamps'] = 'Rakamin'

# Bisa dilanjutkan, sampai tahap lebih detail tetapi setelah melihat value count sudah cukup kompetitor yang banyak diketahui student.
# It can be continued, to a more detailed stage, but after seeing the value count, there are enough competitors that many students know.

In [25]:
other_bootcamps_dataframe.tail(3)

     other_bootcamps  transact_code grouped_bootcamps
1337           binus          17383             binus
1338           revou          17384             RevoU
1339       algoritma          17384         algoritma

In [26]:
other_bootcamps_dataframe['other_bootcamps'].value_counts()

other_bootcamps
revou                                                    234
hacktiv8                                                  86
myskill                                                   70
                                                          60
binar academy                                             44
dibimbing                                                 43
binar                                                     40
rakamin                                                   35
hactiv8                                                   30
udemy                                                     21
pacmann                                                   20
dibimbingid                                               19
hacktiv                                                   17
jayjay                                                    16
hacktive8                                                 15
bsd                                                       14
algoritma                                                 13
dqlab                                                     12
harisenin                                                 12
purwadhika                                                11
tidak ada                                                 11
jakarta                                                   11
coursenet                                                 11
binaracademy                                              10
hacktive                                                  10
belajarlagi                                                9
refocus                                                    8
hactiv                                                     8
digital skola                                              8
digital marketing                                          7
tidak tahu                                                 7
revo u                                                     7
kelaswork                                                  7
batam                                                      7
belajarlagihq                                              6
digitalskola                                               6
coursera                                                   6
dicoding                                                   6
bandung                                                    6
rakamin academy                                            6
skill academy                                              5
tidak mengetahui                                           5
hackativ8                                                  5
visual design                                              5
skilvul                                                    4
practicum                                                  4
tempat belajar                                             4
codemaster                                                 4
dumet school                                               4
yogyakarta                                                 4
uiux                                                       4
surabaya                                                   4
bwa                                                        4
hactive8                                                   4
hackactive                                                 4
eduwork                                                    4
harisenincom                                               4
belajar lagi                                               4
hacktiv8id                                                 4
na                                                         4
sanbercode                                                 4
tempatbelajar                                              4
bolehbelajar                                               4
google                                                     3
hackative                                                  3
tempat belajar id                                          3
myskillid                                                  3
boleh belajar                                              3
jogja                                                      3
kelascom                                                   3
revo                                                       3
poco                                                       2
jay jay                                                    2
qoursenet                                                  2
couse                                                      2
geti inkubator                                             2
job accelerator                                            2
ruang 412                                                  2
revoui                                                     2
haktive                                                    2
enigma                                                     2
pacmannai                                                  2
refactory                                                  2
course net                                                 2
harse                                                      2
kursus desain grafis binus center                          2
binar hackitiv dan revou                                   2
dll                                                        2
domestika                                                  2
revou myskill                                              2
apiary                                                     2
pixelninja                                                 2
coloso                                                     2
purwadika                                                  2
sekolah koding                                             2
hectiv8                                                    2
skillsid                                                   2
binaraacademy                                              2
sadasa                                                     2
hacktivate                                                 2
l                                                          2
skillful                                                   2
habis kerja                                                2
ruang guru                                                 2
pacmann academy                                            2
saya tidak tau                                             2
tidak tau                                                  2
alterra academy                                            2
aiforindonesia                                             2
enter                                                      2
general assembly                                           2
developer school                                           2
green academy                                              2
idf                                                        2
kelascoding                                                2
dm elite                                                   2
arkademy                                                   2
pijar                                                      2
tidak aada                                                 2
g2 academy                                                 2
data scince                                                2
reviu                                                      2
z                                                          2
myskillacademia                                            2
akademia                                                   2
2kademi                                                    2
hackatktive                                                2
green academy indonesia                                    2
data science                                               2
zetta camp                                                 2
clevio                                                     2
bisa ai                                                    2
sbdm                                                       2
impact byte                                                2
fazztrack                                                  2
metrodata                                                  2
tangerang                                                  2
enigma camp                                                2
full stack web development                                 2
teamalgoritma                                              2
myskillidbinar                                             2
practicuum                                                 2
haktiv8id                                                  2
bandung jakarta surabaya                                   2
kagglecom                                                  2
bumi serpong damai                                         2
revoucom                                                   2
myskillcom                                                 2
hactive8id                                                 2
binary                                                     2
dealls                                                     2
hactivi8                                                   2
kontan academy                                             2
revouid                                                    2
orami mungkin                                              2
tempat belajarid                                           2
digital skoola                                             2
narasiodata                                                2
belum mengetahui bootcamp lainnya                          2
dqlabs                                                     2
ui ux design                                               2
product management                                         2
revouco                                                    2
habiskerja                                                 2
coding bee                                                 2
hariseninmillenialschool                                   2
purwardhika                                                2
schoters                                                   2
karirpad                                                   2
revoupacman                                                2
edspert                                                    2
alterra                                                    2
villa merah  bimbel  kelas kreatif artakarya  bimbel       2
 revou                                                     2
youtube university                                         2
coding studio                                              2
myskill id                                                 2
rekamin academy                                            2
hectiv                                                     2
hackativ                                                   2
hackactiv                                                  2
binus center                                               2
binus                                                      2
sinergiid                                                  1
enigmacamp                                                 1
my skill                                                   1
saltacademyid                                              1
alden wattimena                                            1
hacktive9                                                  1
idx partners                                               1
arkademi                                                   1
dumetschool                                                1
hatching academy                                           1
impactbyte                                                 1
dimbimbing                                                 1
rakaminacademy                                             1
jjschool                                                   1
pacman                                                     1
revvou                                                     1
skillid                                                    1
remote work                                                1
rwid                                                       1
arrays classroomqueries classroom                          1
binus centre                                               1
raya school                                                1
kelaskerja                                                 1
codingstudio                                               1
lingkaran                                                  1
Name: count, dtype: int64

#### **Update value admission score & informative_website**

The survey transaction form is updated from time to time, make sure the data matches the interpretation with the latest data.

In [27]:
df['informative_website'].unique()

array(['Sangat Baik', 'Buruk', 'Baik', 'Memadai', None, 'Kurang Baik',
       'Cukup'], dtype=object)

In [28]:
df['informative_website'].value_counts()

informative_website
Memadai        97
Baik           94
Buruk          93
Kurang Baik    93
Sangat Baik    92
Cukup          92
Name: count, dtype: int64

In [29]:
df['admission_score'].unique()

array([None, 'Sangat Baik', 'Cukup', 'Kurang Baik', 'Baik', 'Memadai',
       'Buruk'], dtype=object)

In [30]:
df['admission_score'].value_counts()

admission_score
Sangat Baik    227
Baik           184
Cukup           35
Memadai         28
Kurang Baik      3
Buruk            1
Name: count, dtype: int64

In [31]:
# Mapping dictionary
# Karena dulu hanya ada opsi Kurang Baik, Memadai, Sangat Baik, sehingga value kurang baik dan Memadai harus di adjust ke data baru.
# Because previously there were only the options Less Good, Adequate, Very Good, so the Less Good and Adequate values ​​had to be adjusted to the new data.
score_mapping = {
  'Cukup': 'Memadai',       # 'Cukup' = Fair / Adequate
  'Kurang Baik': 'Buruk'    # 'Kurang Baik' = Poor
}

# Apply the mapping
df['admission_score'] = df['admission_score'].replace(score_mapping)
df['informative_website'] = df['informative_website'].replace(score_mapping)

In [32]:
df['admission_score'].value_counts()

admission_score
Sangat Baik    227
Baik           184
Memadai         63
Buruk            4
Name: count, dtype: int64

### **Upload to Big Query**

In [33]:
# Installing required libraries
#!pip install google.oauth2
#!pip install bigquery
#!pip install pandas_gbq

In [34]:
from google.cloud import bigquery
from pandas.io import gbq
from google.oauth2 import service_account
import pandas_gbq

In [35]:
# Setting credential info
credentials_info = {
  "type": "service_account",
  "project_id": "dummy-database-439607",
  "private_key_id": "0acc57ee1caf7f39b7349070cc4f7cfc0552f73b",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4OWqhxk+6vP6h\n9Jx5MEUrxaPpx+HDjijfLXZlfmqlJhT/dEmychLEjvOPKXjT2yBHmRNw+77glso5\npvnd+B4sol24tn7aepi/feZNcmwgxGfNF0Iq26dA9FlyJMlAFlkrFQLbtCJdgvhT\nukW8fwtWzO2kg/p3qGvN4w0auDl+iFlnY+NeUfxuREKR4yqaq+VtOJAbTa92JBSH\nZ21ZKA9pv779Q/iL+MdhZl6U0WrcO35Z9fjo1J6Lvn46zAjKW+0iv4uqV0XESX8H\nZuoacIJDlRHERAf6m78cY34OXUmNRN1ePll6RJfunKo1nGthZLUyPzDKE/rKmPH0\nsUvXW9lnAgMBAAECggEACwPP1t1jHgC33tof0vUqZZwbGVrMqmMhGXr/5cChwr8c\nqUt8LpG4go0jje9GXLBw5ScHbQ14U7hgXgMYVIfF0hhhLy6mNgz3fheagg3x3iGw\nLSiTWbmpbe5OPM9rQwwzB6rpcVZ7aYjvrR3ploQoGugE233Sp33n+Db3rR3Pvjtx\nhiBK3uQ9nnsKo6mSxLNy3vygG/qxMzA0HA0gRkLFa9RaKL/LgExzoEBqCPlvt/7H\n05xlFIXDUI8cFo40Hzd8hhIM7BmVIMTclqwaU5raCfeshfQi31W3VFQamaaU/k+e\nO08Jj/u1rSrk33LN4yxqO0RRibp2tz6II1MaKknVEQKBgQD+O2vDxId83mDl7qzr\n7pkBCLyxy68+bt9ZvNRmisxSGBK5M//iTRcyu++iB74HafLb5Da7cY7ZqD+Wgm6K\n/bkroXc3bcFFi5hq+kyTAaJjyj3kYTMYQLedIf/kKBAXzNJHmkQMr+VrE+/FwtP0\nEOhyzcGLQtbFnyuFEvceLwS48QKBgQC5gV53AHObcal4fOn5qiHhhawb8a+L64JR\nQ9BA09fbVQXGkluwD8fP/IPREoQz48vt2/FvQO1jAGjhA1BIbdVOdAP144GzXnyH\nW7/COfL01lNSx9yVvAI0/IyiPtA03KnR15/0l5d67tNN743POAgjtSvlvuauJjeq\nXiJ66zT31wKBgD7Z3dh2G7DJIVd23BUv1W+mA1BJNLfQnTMINdJr+ftJrEdRDa+a\ns2N9hs6d72LR1JJ8JvPMLS6uI5pIAKAn/cFFl72CSsewrSu1WXz2aHkXJJnzVbhn\nN32HTEXRibj4j/vXrX8ddTA1q49OjSvHik/ngjO1gHc21IF/oMw7f4VhAoGAAVVL\nr4FCU3CqriH/sHqnia5jQUQoZdIIersJCR48o+flhbrRi99hKT6AWAVRC+psMcZt\n4sXNrvN2zX8vmYWojcrJqH+9E+Pu8y4Wn7e45keQC71B+ZWDUowqGpRm/KpFUivB\ni4l3XjvPKvU4yK93Z4JK0XjgwYmmxsOsbcO4+rsCgYEA9BRYFzSpo4OYJah7yXGP\nZWAtF+b/6yWYX0llT3O91q6nIUxkg6nMf4dPTOuoPkrG5s1koqv/FqPluiVMIK5x\n5xMcZmVwP6oHCjpns0ZAtjLv+Q0+v8DRcSpmmkPLqNxD8sVJ7orHRS99m2s4O5tt\nyXnEnANY+X4BNHtiSFIpJo8=\n-----END PRIVATE KEY-----\n",
  "client_email": "dummy-data-base@dummy-database-439607.iam.gserviceaccount.com",
  "client_id": "105275593668281852109",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/dummy-data-base%40dummy-database-439607.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

In [36]:
project_id = 'dummy-database-439607'
dataset_id = 'dummy_transaction'
table_transact = f'{dataset_id}.transaction'
table_choosing_reason = f'{dataset_id}.choosing_reason'
table_registration_reason = f'{dataset_id}.registration_reason'
table_other_bootcamp = f'{dataset_id}.other_bootcamp'

scopes = ["https://www.googleapis.com/auth/bigquery"]
credentials = service_account.Credentials.from_service_account_info(credentials_info, scopes=scopes)

In [37]:
pandas_gbq.to_gbq(df, table_transact, project_id=project_id, if_exists='replace', credentials=credentials)

In [38]:
pandas_gbq.to_gbq(choosing_reason_dataframe, table_choosing_reason, project_id=project_id, if_exists='replace', credentials=credentials)

In [39]:
pandas_gbq.to_gbq(registration_reason_dataframe, table_registration_reason, project_id=project_id, if_exists='replace', credentials=credentials)

In [40]:
pandas_gbq.to_gbq(other_bootcamps_dataframe, table_other_bootcamp, project_id=project_id, if_exists='replace', credentials=credentials)

### **Upload to G-Sheet**

In [ ]:
#!pip install gspread #Installing googlespreadsheet library

In [42]:
import gspread
from google.oauth2.service_account import Credentials
credentials = Credentials.from_service_account_info(credentials_info)
client = gspread.authorize(credentials)

In [43]:
# Define the scopes you need (Google Sheets API)
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

# Create a credentials object with the necessary scopes
credentials = Credentials.from_service_account_info(credentials_info, scopes=scopes)

# Authorize and create a gspread client
client = gspread.authorize(credentials)

# Open the spreadsheet by its name
spreadsheet = client.open('Dummy Transaction')

# Access the specific worksheets
transaction_worksheet = spreadsheet.worksheet('transaction')
choosing_reason_worksheet = spreadsheet.worksheet('choosing_reason')
registration_reason_worksheet = spreadsheet.worksheet('registration_reason')
other_bootcamps_worksheet = spreadsheet.worksheet('other_bootcamps')

### ***Worksheet format can only be int, string, make sure there are no other formats**

In [44]:
def process_numeric_columns(df):
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            if df[col].apply(lambda x: x.is_integer() if isinstance(x, float) else True).all():
                # Convert to integer if all float values are whole numbers
                df[col] = df[col].astype(int)
            else:
                # Convert to string if any float values have decimals
                df[col] = df[col].astype(str)
        else:
            # Ensure all non-numeric columns are string
            df[col] = df[col].astype(str)
    return df

df = process_numeric_columns(df)

In [45]:
transaction_worksheet.update([df.columns.values.tolist()] + df.values.tolist())

{'spreadsheetId': '1wD6HqeA2cL1VgjekMB_ANqPO0PBo1LeRcHQ04qW5YWQ',
 'updatedRange': 'transaction!A1:AJ654',
 'updatedRows': 654,
 'updatedColumns': 36,
 'updatedCells': 23544}

In [46]:
# Checking 'transaction' worksheets
work_sheet = spreadsheet.worksheet('transaction')
data_transcation_worksheet = work_sheet.get_all_values()
data_transcation_worksheet = pd.DataFrame(data_transcation_worksheet)
data_transcation_worksheet.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
0,transact_code,invoice_created_at,transaction_created_date,user_code,subtotal_amount,total_discount_amount,final_price,receivable_amount,created_by,invoice_code,order_confirmation_code,quantity,transaction_status,program_name,branch_name,program_category,study_method,study_schedule,program_start_date,program_end_date,program_start_time,program_end_time,program_days,referral_source,user_email,user_city,birth_date,registration_reason,time_knowing_program,choosing_reason,content_source,other_bootcamps,first_time_knowledge,informative_website,admission_score,student_age
1,9343,2023-01-09 11:19:57+07:00,2023-01-06 13:11:30+07:00,23783,7770000,0,7770000,0,admission1,INV/2023/01/09/0005,ON/2023/01/06/0008,1,Paid,Data Analytics,Purwadhika Livestream Class,Skill Accelerator Bootcamp,Livestream Class,After Hour Training,2023-01-23 17:00:00,2023-03-13 17:00:00,19:00,22:00,Tue & Thur,Social Media Purwadhika,users36@gmail.com,Jambi,2000-08-21,"Karena promo yang akan segera berakhir,Waktu belajar yang akhirnya tersedia,Dana belajar yang akhirnya sudah terkumpul,Kebutuhan untuk segera mendapatkan pekerjaan,Perintah dari Orang Tua/Keluarga,Tergerak karena promo yang menarik",1 - 3 Bulan,"Kredibilitas Purwadhika sejak tahun 1987,Kisah sukses dari para Alumni Purwadhika",Instagram,"Hacktiv8, binaracademy, dibimbing.id",None,Sangat Baik,None,22.0
2,9358,2023-01-09 15:22:25+07:00,2023-01-09 14:58:05+07:00,23328,46065000,13319500,32745500,0,admission2,INV/2023/01/09/0026,ON/2023/01/09/0010,1,Paid,Job Connector Bootcamp Full Stack Web Development,Purwadhika Campus BSD,Job Connector,On Campus,Full Time Training,2023-06-25 17:00:00,2023-09-18 17:00:00,09:00,16:00,Mon-Fri,Social Media Influencer,users31@gmail.com,Batam,1999-08-30,"Karena promo yang akan segera berakhir,Waktu belajar yang akhirnya tersedia,Kebutuhan untuk segera mendapatkan pekerjaan,Perintah dari Orang Tua/Keluarga",6 bulan - 1 tahun,"Kredibilitas Purwadhika sejak tahun 1987,Fasilitas kampus Purwadhika,Kisah sukses dari para Alumni Purwadhika,Materi/Silabus/Kurikulum Purwadhika,Rekomendasi dari seseorang,Jadwal Intake yang sesuai kebutuhan",Tidak ada,"RevoU , Hacktiv8, Myskill, Habiskerja",Ya,Buruk,None,23.0

In [47]:
choosing_reason_worksheet.update([choosing_reason_dataframe.columns.values.tolist()] + choosing_reason_dataframe.values.tolist())

{'spreadsheetId': '1wD6HqeA2cL1VgjekMB_ANqPO0PBo1LeRcHQ04qW5YWQ',
 'updatedRange': 'choosing_reason!A1:B2408',
 'updatedRows': 2408,
 'updatedColumns': 2,
 'updatedCells': 4816}

In [48]:
# worksheet 'choosing_reason'
work_sheet = spreadsheet.worksheet('choosing_reason')
data_choosing_reason_worksheet = work_sheet.get_all_values()
data_choosing_reason_worksheet = pd.DataFrame(data_choosing_reason_worksheet)
data_choosing_reason_worksheet.head(3)

                                          0              1
0                           choosing_reason  transact_code
1  Kredibilitas Purwadhika sejak tahun 1987           9343
2  Kisah sukses dari para Alumni Purwadhika           9343

In [49]:
registration_reason_worksheet.update([registration_reason_dataframe.columns.values.tolist()] + registration_reason_dataframe.values.tolist())

{'spreadsheetId': '1wD6HqeA2cL1VgjekMB_ANqPO0PBo1LeRcHQ04qW5YWQ',
 'updatedRange': 'registration_reason!A1:B1730',
 'updatedRows': 1730,
 'updatedColumns': 2,
 'updatedCells': 3460}

In [50]:
# worksheet 'registration_reason'
work_sheet = spreadsheet.worksheet('registration_reason')
data_registration_reason_worksheet = work_sheet.get_all_values()
data_registration_reason_worksheet = pd.DataFrame(data_registration_reason_worksheet)
data_registration_reason_worksheet.head(3)

                                        0              1
0                     registration_reason  transact_code
1  Karena promo yang akan segera berakhir           9343
2    Waktu belajar yang akhirnya tersedia           9343

In [51]:
other_bootcamps_worksheet.update([other_bootcamps_dataframe.columns.values.tolist()] + other_bootcamps_dataframe.values.tolist())

{'spreadsheetId': '1wD6HqeA2cL1VgjekMB_ANqPO0PBo1LeRcHQ04qW5YWQ',
 'updatedRange': 'other_bootcamps!A1:C1341',
 'updatedRows': 1341,
 'updatedColumns': 3,
 'updatedCells': 4019}

In [52]:
# worksheet 'other_bootcamps'
work_sheet = spreadsheet.worksheet('other_bootcamps')
data_other_bootcamps_worksheet = work_sheet.get_all_values()
data_other_bootcamps_worksheet = pd.DataFrame(data_other_bootcamps_worksheet)
data_other_bootcamps_worksheet.head(3)

                 0              1                  2
0  other_bootcamps  transact_code  grouped_bootcamps
1         hacktiv8           9343           Hacktiv8
2     binaracademy           9343      Binar Academy

In [53]:
work_sheet = spreadsheet.get_worksheet(0) # gets first worksheet
data_1 = work_sheet.get_all_values()
data_1 = pd.DataFrame(data_1)
data_1.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
0,transact_code,invoice_created_at,transaction_created_date,user_code,subtotal_amount,total_discount_amount,final_price,receivable_amount,created_by,invoice_code,order_confirmation_code,quantity,transaction_status,program_name,branch_name,program_category,study_method,study_schedule,program_start_date,program_end_date,program_start_time,program_end_time,program_days,referral_source,user_email,user_city,birth_date,registration_reason,time_knowing_program,choosing_reason,content_source,other_bootcamps,first_time_knowledge,informative_website,admission_score,student_age
1,9343,2023-01-09 11:19:57+07:00,2023-01-06 13:11:30+07:00,23783,7770000,0,7770000,0,admission1,INV/2023/01/09/0005,ON/2023/01/06/0008,1,Paid,Data Analytics,Purwadhika Livestream Class,Skill Accelerator Bootcamp,Livestream Class,After Hour Training,2023-01-23 17:00:00,2023-03-13 17:00:00,19:00,22:00,Tue & Thur,Social Media Purwadhika,users36@gmail.com,Jambi,2000-08-21,"Karena promo yang akan segera berakhir,Waktu belajar yang akhirnya tersedia,Dana belajar yang akhirnya sudah terkumpul,Kebutuhan untuk segera mendapatkan pekerjaan,Perintah dari Orang Tua/Keluarga,Tergerak karena promo yang menarik",1 - 3 Bulan,"Kredibilitas Purwadhika sejak tahun 1987,Kisah sukses dari para Alumni Purwadhika",Instagram,"Hacktiv8, binaracademy, dibimbing.id",None,Sangat Baik,None,22.0
2,9358,2023-01-09 15:22:25+07:00,2023-01-09 14:58:05+07:00,23328,46065000,13319500,32745500,0,admission2,INV/2023/01/09/0026,ON/2023/01/09/0010,1,Paid,Job Connector Bootcamp Full Stack Web Development,Purwadhika Campus BSD,Job Connector,On Campus,Full Time Training,2023-06-25 17:00:00,2023-09-18 17:00:00,09:00,16:00,Mon-Fri,Social Media Influencer,users31@gmail.com,Batam,1999-08-30,"Karena promo yang akan segera berakhir,Waktu belajar yang akhirnya tersedia,Kebutuhan untuk segera mendapatkan pekerjaan,Perintah dari Orang Tua/Keluarga",6 bulan - 1 tahun,"Kredibilitas Purwadhika sejak tahun 1987,Fasilitas kampus Purwadhika,Kisah sukses dari para Alumni Purwadhika,Materi/Silabus/Kurikulum Purwadhika,Rekomendasi dari seseorang,Jadwal Intake yang sesuai kebutuhan",Tidak ada,"RevoU , Hacktiv8, Myskill, Habiskerja",Ya,Buruk,None,23.0